# Generated by Django 5.1.6 on 2025-03-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_remove_resume_updated_at_resume_contact_linkedin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='contact_linkedin',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='contact_website',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='experiences',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='projects',
        ),
        migrations.AddField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
